// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
/// NOTE: These values (apiKey, appId, projectId, etc.) are NOT secrets.
/// They are safe to ship inside a compiled client app and are meant to be
/// public — this is how the FlutterFire CLI generates this file by default.
/// Real protection comes from Firestore/Auth Security Rules and from
/// restricting each key to specific app package names / bundle ids in the
/// Google Cloud console, not from hiding these values behind an env file.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcNvj22nkC2JtMHBiy99KJd2HNtzBMvFk',
    appId: '1:412008211649:web:c603947769f4d2d181e040',
    messagingSenderId: '412008211649',
    projectId: 'chat-app-29c66',
    authDomain: 'chat-app-29c66.firebaseapp.com',
    storageBucket: 'chat-app-29c66.firebasestorage.app',
    measurementId: 'G-6NWFH45DB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHDaOyu6trAvZF_KKpirZcD0QsjViWKvo',
    appId: '1:412008211649:android:53015637764dc4bf81e040',
    messagingSenderId: '412008211649',
    projectId: 'chat-app-29c66',
    storageBucket: 'chat-app-29c66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiyg8xEYhb9shPTXDvl3hUJWdn2sYCSsw',
    appId: '1:412008211649:ios:6e938293b25c80d681e040',
    messagingSenderId: '412008211649',
    projectId: 'chat-app-29c66',
    storageBucket: 'chat-app-29c66.firebasestorage.app',
    iosBundleId: 'com.example.LetsChat',
  );

  // macOS shares the iOS app registration (same appId/bundle id), so it
  // reuses the iOS API key. Previously this read a FIREBASE_API_KEY_MACOS
  // .env value that was never defined, which would have thrown a null
  // check error at runtime the first time the app ran on macOS.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiyg8xEYhb9shPTXDvl3hUJWdn2sYCSsw',
    appId: '1:412008211649:ios:6e938293b25c80d681e040',
    messagingSenderId: '412008211649',
    projectId: 'chat-app-29c66',
    storageBucket: 'chat-app-29c66.firebasestorage.app',
    iosBundleId: 'com.example.LetsChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcNvj22nkC2JtMHBiy99KJd2HNtzBMvFk',
    appId: '1:412008211649:web:4c1134a23db8b2e381e040',
    messagingSenderId: '412008211649',
    projectId: 'chat-app-29c66',
    authDomain: 'chat-app-29c66.firebaseapp.com',
    storageBucket: 'chat-app-29c66.firebasestorage.app',
    measurementId: 'G-DGNVYW8VB3',
  );
}
